/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef dinoisland_CONSTANTS_H
#define dinoisland_CONSTANTS_H

#include "dinoisland_types.h"



class dinoislandConstants {
 public:
  dinoislandConstants();

};

extern const dinoislandConstants g_dinoisland_constants;



#endif
