/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "dinoisland_constants.h"



const dinoislandConstants g_dinoisland_constants;

dinoislandConstants::dinoislandConstants() {
}



